package me.parkdaiho.project.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum Press {

    KHAN("KYUNGHYANG"), KMIB("KOOKMIN"), DONGA("DONGA"), MUNHWA("MUNHWA"), SEOUL("SEOUL"), SEGYE("SEGYE"),
    CHOSUN("CHOSUN"), JOONGANG("JOONGANG"), HANI("HANGYEORE"), HANKOOKILBO("HANKOOKILBO"), NEWS1("NEWS1"),
    NEWSIS("NEWSIS"), YNA("YEONHAB"), YONHABNEWSTV("YONHABNEWSTV"), ICHANNELA("CHANNELA"), WOWTV("HANKOOKGYUNGJETV"),
    JTBC("JTBC"), KBS("KBS"), IMBC("MBC"), MBN("MBN"), SBS("SBS"), SBS_BIZ("SBS_BIZ"), TVCHOSUN("TVCHOSUN"), YTN("YTN"),
    MK("MAILKYUNGJE"), MT("MONEYTODAY"), BIZWATCH("BIZWATCH"), SEDAILY("SEOULKYUNNJE"), ASIAE("ASIAKYUNGJE"),
    EDAILY("EDAILY"), CHOSUN_BIZ("CHOSUN_BIZ"), JOSEILBO("JOSEILBO"), FNNEWS("FINANCIALNEWS"), HANKYUNG("HANKYUNG"),
    HERALDCORP("HERALDKYUNGJE"), NOCUTNEWS("NOCUTNEWS"), TF("THEFACTNEWS"), DAILIAN("DAILIAN"), MONEYS("MONEYS"),
    MEDIATODAY("MEDIATODAY"), INEWS24("INEWS24"), OHMYNEWS("OHMYNEWS"), PRESSIAN("PRESSIAN"), DDAILY("DIGITALDAILY"),
    DT("DIGITALTIMES"), BLOTER("BLOTER"), ETNEWS("ETNEWS"), ZDNET("ZDNETKOREA"), THESCOOP("THESCOOP"), LADY("LADY_KYUNGHYANG"),
    SISAIN("SISAIN"), SISAJOURNAL("SISAJOURNAL"), SHINDONGA("SHINDONGA"), SAN("SANCHOSUN"), ECONOMIST("ECONOMIST"),
    WEEKLY_KHAN("WEEKLY_KYUNGHYANG"), WEEKLY_DONGA("WEEKLY_DONGA"), WEEKLY_CHOSUN("WEEKLY_CHOSUN"), H21("HANGYEORE21"),
    MAGAZINE_HANKYUNG("MAGAZINE_HANKYUNG"), JOURNALIST("JOURNALIST_SASSOCIATION_OF_KOREA"), NONGMIN("NONGMIN"),
    NEWSTAPA("NEWSTAPA"), DONGASCIENCE("DONGASCIENCE"), WOMENNEWS("WOMENNEWS"), ILDARO("ILDARO"),
    KOREAJOONGANGDAILY("KOREAJOONGANGDAILY"), KOREAHERALD("KOREAHERALD"), KORMEDI("KORMEDI"), HEALTH_CHOSUN("HEALTH_CHOSUN"),
    KADO("KANGWONDOMINILBO"), KWNEWS("KANGWONILBO"), KYEONGGI("KYEONGGIILBO"), KOOKJE("KOOKJE"), DGMBC("DAEGU_MBC"),
    DAEJONILBO("DAEHONILBO"), IMAEIL("MAEILSHINMUN"), BUSAN("BUSANILBO"), JMBC("JEONJU_MBC"), CJB("CHUNGJUBANGSONG"),
    JIBS("JIBS"), IKBC("KBC");

    private final String press;
}
