spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google

          naver:
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1800

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: eogh7204@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

jwt:
  oauth2-authorization-request-cookie-name: "oauth2_auth_request"
  oauth2-authorization-request-duration-of-seconds: 180

  issuer: eogh7204@gmail.com
  secret-key: token-secret-key

  refresh-token-cookie-name: refresh_token
  refresh-token-duration-of-days: 1
  access-token-duration-of-hours: 1

  authorization-header-name: Authorization
  authorization-token-prefix: "Bearer "

# jsp 변경 시 바로 적용
server:
  servlet:
    jsp:
      init-parameters:
        development: true

naver:
  search:
    base-url: https://openapi.naver.com
    news-search-path: "/v1/search/news.json"
    client-id-header-name: X-Naver-Client-Id
    client-secret-header-name: X-Naver-Client-Secret
    client-id: ${NAVER_SEARCH_CLIENT_ID}
    client-secret: ${NAVER_SEARCH_CLIENT_SECRET}
    display: 10 # pagination-news-items-per-page

file:
  upload:
    location: "/Users/parkdaeho/develop/workspace/developing-project/src/main/resources/static/upload"

pagination :
  users-per-page: 9
  user-pages-per-block: 10
  article-list-in-articles: 10
  posts-per-page: 20
  post-pages-per-block: 10
  comments-per-page: 5
  comment-pages-per-block: 5
  index-views: 10
  news-items-per-page: 10
  news-pages-per-block: 10
  notice-per-page: 20
  fixed-notice-per-page: 5
  notice-pages-per-block: 10
  clippings-per-page: 10
  clippings-pages-per-block: 10
  my-posts-per-page: 20
  my-posts-pages-per-block: 10
  my-comments-per-page: 20
  my-comments-pages-per-block: 10

  page-name: "page"
  total-pages-name: "totalPages"
  total-elements-name: "totalElements"
  start-num-of-page-block-name: "startNumOfPageBlock"
  last-num-of-page-block-name: "lastNumOfPageBlock"
  next-page-name: "nextPage"
  previous-page-name: "previousPage"

cookie :
  saved-username-name: "SAVED-USERNAME"

  viewed-articles-name: "VIEWED-ARTICLES"
  viewed-posts-name: "VIEWED-POSTS"
  viewed-notice-name: "VIEWED-NOTICE"

  username-in-find-username-name: "FIND-USERNAME"
  email-in-find-password-name: "FIND-PASSWORD"

  saved-username-expiry: 31536000
  viewed-checked-expiry: 86400
  find-user-info-expiry: 1800
