-- INSERT ADMINISTRATOR
INSERT
INTO
    USERS
(ID, CREATED_AT, EMAIL, IS_ENABLED, MODIFIED_AT, NICKNAME, PASSWORD, PROVIDER, ROLE, USERNAME)
VALUES
    (DEFAULT, CURRENT_DATE, 'EMAIL', 'TRUE', CURRENT_DATE, 'ADMIN', 'admin', 'SELF', 'ADMIN', 'admin');

-- INSERT TEST_USER
INSERT
INTO
    USERS
(ID, CREATED_AT, EMAIL, IS_ENABLED, MODIFIED_AT, NICKNAME, PASSWORD, PROVIDER, ROLE, USERNAME)
VALUES
    (DEFAULT, CURRENT_DATE, 'TEST', 'TRUE', CURRENT_DATE, 'TEST', 'test', 'SELF', 'USER', 'test');
